# Generated by Django 5.2.3 on 2025-11-11 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('photo', models.ImageField(upload_to='course/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('status', models.CharField(choices=[('complete', 'Completado'), ('inprocess', 'En Proceso'), ('notapproved', 'No aprovado'), ('notstarted', 'No inciado')], default='notstarted', max_length=50, verbose_name='Estado')),
                ('percentaje', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avance de Curso')),
                ('lessons', models.IntegerField(default=0, verbose_name='Lecciones')),
                ('enable', models.BooleanField(default=True, verbose_name='Habilitado/Inhabilitado')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título de la lección')),
                ('content', models.TextField(blank=True, verbose_name='Contenido')),
                ('video_url', models.URLField(blank=True, verbose_name='Video')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden en el curso')),
                ('status', models.CharField(choices=[('complete', 'Completado'), ('inprocess', 'En Proceso'), ('notapproved', 'No aprobado'), ('notstarted', 'No iniciado')], default='notstarted', max_length=50, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['order'],
            },
        ),
    ]
