# Generated by Django 5.2.3 on 2025-11-11 20:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo de cuenta')),
            ],
            options={
                'verbose_name': 'Tipo de Cuenta',
                'verbose_name_plural': 'Tipos de Cuenta',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='AgencyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('n', 'N – Comisión 10%'), ('d', 'D – Comisión 14%'), ('c', 'C – Comisión 18%'), ('b', 'B – Comisión 22%'), ('a', 'A – Comisión 26%'), ('s', 'S – Comisión 30%')], default='n', max_length=1, verbose_name='Nivel de agencia')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Nombre del grupo')),
            ],
            options={
                'verbose_name': 'Nivel de Agencia',
                'verbose_name_plural': 'Niveles de Agencia',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('streamer_name', models.CharField(max_length=150, verbose_name='Nombre de la Streamer')),
                ('total_diamonds', models.PositiveIntegerField(verbose_name='Diamantes totales')),
                ('diamonds_chat', models.PositiveIntegerField(verbose_name='Diamantes por chat')),
                ('diamonds_gifts', models.PositiveIntegerField(verbose_name='Diamantes por regalitos')),
                ('diamonds_video', models.PositiveIntegerField(verbose_name='Diamantes por videollamadas')),
            ],
            options={
                'verbose_name': 'Rendimiento Diario',
                'verbose_name_plural': 'Rendimientos Diarios',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto en USD')),
                ('withdrawal_date', models.DateField(verbose_name='Fecha del retiro')),
            ],
            options={
                'verbose_name': 'Retiro',
                'verbose_name_plural': 'Retiros',
                'ordering': ['-withdrawal_date'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Nombre del grupo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Grupo de Retiro',
                'verbose_name_plural': 'Grupos de Retiro',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID SUGO')),
                ('name', models.CharField(max_length=150, verbose_name='Apodo')),
                ('real_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre real')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='streamers/profile_pics/', verbose_name='Foto de perfil')),
                ('telegram_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Telegram')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de WhatsApp')),
                ('join_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('country', models.CharField(choices=[('col', 'Colombia'), ('ven', 'Venezuela'), ('mex', 'Mexico'), ('bol', 'Bolivia'), ('per', 'Perú'), ('arg', 'Argentina'), ('ecu', 'Ecuador'), ('crc', 'Costa Rica')], max_length=15, verbose_name='País')),
                ('vip_level', models.CharField(choices=[('0', 'VIP 0'), ('1', 'VIP 1'), ('2', 'VIP 2'), ('3', 'VIP 3'), ('4', 'VIP 4'), ('5', 'VIP 5'), ('6', 'VIP 6'), ('7', 'VIP 7'), ('8', 'VIP 8')], max_length=10, verbose_name='Nivel VIP')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('new', 'Nueva'), ('intermediate', 'Intermedia'), ('newbie', 'Novata'), ('resting', 'Descanso'), ('no_income_7', '7 días sin generar'), ('no_income_15', '15 días sin generar'), ('no_income_30', '30 días sin generar'), ('waiting_sugo', 'Esperando aprobación'), ('my_agency_btn', 'Botón Mi Agencia'), ('duplicate', 'Duplicado'), ('released', 'Liberada')], default='new', max_length=50, verbose_name='Estado')),
                ('charm_level', models.IntegerField(choices=[(0, 'Nivel 0 – Nueva'), (1, 'Nivel 1 – Principiante +5,000 diamantes'), (2, 'Nivel 2 – Intermedia +25,000 diamantes'), (3, 'Nivel 3 – Activa +100,000 diamantes'), (4, 'Nivel 4 – Activa +450,000 diamantes'), (5, 'Nivel 5 – Activa +2,045,000 diamantes')], default=0, verbose_name='Nivel de Encanto')),
                ('account_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cuenta para recibir dinero')),
                ('qr_binance_picture', models.ImageField(blank=True, null=True, upload_to='streamers/qr_binance/', verbose_name='QR de Binance')),
                ('binance_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID de Binance')),
                ('is_capacite', models.BooleanField(default=False, verbose_name='¿Ya Fue Capacitada?')),
                ('date_capacite', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Capacitación')),
                ('reuse_acount', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cuenta Reuzada')),
                ('enable', models.BooleanField(default=True, verbose_name='Habilitado/Inhabilitado')),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sugo.accounttype', verbose_name='Tipo de cuenta')),
            ],
            options={
                'verbose_name': 'Streamer',
                'verbose_name_plural': 'Streamers',
                'ordering': ['-join_date'],
            },
        ),
    ]
