# Generated by Django 5.2.3 on 2025-11-11 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sugo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado'),
        ),
        migrations.AddField(
            model_name='dailyperformance',
            name='streamer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sugo.streamer', verbose_name='Streamer'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='streamer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sugo.streamer', verbose_name='Streamer'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='sugo.withdrawalgroup', verbose_name='Grupo de retiro'),
        ),
    ]
